# Generated by Django 5.1.4 on 2024-12-19 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDeVeiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_registro', models.IntegerField()),
                ('data_entrada', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo_caminhao', models.CharField(choices=[('Carreta Bau', 'Carreta - Baú'), ('Carreta Sider', 'Carreta - Sider'), ('Truck Bau', 'Truck - Baú'), ('Truck Sider', 'Truck - Sider')], max_length=20)),
                ('placa', models.CharField(max_length=7)),
                ('nome_motorista', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('data_lancamento', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
