# Generated by Django 5.1.4 on 2024-12-21 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadeveiculos',
            name='expedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entradadeveiculos',
            name='data_entrada',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='entradadeveiculos',
            name='data_lancamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='entradadeveiculos',
            name='nome_motorista',
            field=models.CharField(max_length=50, verbose_name='Nome do Motorista'),
        ),
        migrations.AlterField(
            model_name='entradadeveiculos',
            name='numero_do_registro',
            field=models.IntegerField(verbose_name='Número do Registro'),
        ),
        migrations.AlterField(
            model_name='entradadeveiculos',
            name='placa',
            field=models.CharField(max_length=7, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='entradadeveiculos',
            name='tipo_caminhao',
            field=models.CharField(choices=[('Carreta Bau', 'Carreta - Baú'), ('Carreta Sider', 'Carreta - Sider'), ('Truck Bau', 'Truck - Baú'), ('Truck Sider', 'Truck - Sider')], max_length=20, verbose_name='Tipo de Caminhão'),
        ),
        migrations.AlterField(
            model_name='entradadeveiculos',
            name='usuario',
            field=models.CharField(max_length=50, verbose_name='Usuário'),
        ),
    ]
